apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-web-bff
  
  labels:
    app: book-web-bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-web-bff
  template:
    metadata:
      labels:
        app: book-web-bff
    spec:
      containers:
      - name: book-web-bff
        image: 813170851015.dkr.ecr.us-east-1.amazonaws.com/book-web-bff:latest # Replace with your image repository and tag
        imagePullPolicy: Always
        env:
        - name: CUSTOMER_SVC_URL
          value: "http://customer-service:8080"
        - name: BOOK_SVC_URL
          value: "http://book-service:8080"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
