apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-web-bff
  namespace: bookstore-ns
  labels:
    app: book-web-bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-web-bff
  template:
    metadata:
      labels:
        app: book-web-bff
    spec:
      containers:
      - name: book-web-bff
        image: book-web-bff:latest # Replace with your image repository and tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10